# Import the Required library

In [1]:
import numpy as np
import pandas as pd
import pickle

# Import the training set and testing set for tarning the model
##### - The link of dataset is https://www.kaggle.com/imohtn/video-games-rating-by-esrb

In [2]:
training_set = pd.read_csv('dataset/Video_games_esrb_rating.csv')
training_set.head(10)

title  console  \
0                         Monster Jam Steel Titans 2        1   
1                             Subnautica: Below Zero        1   
2                  NIER REPLICANT VER.1.22474487139…        1   
3                                         Jamestown+        0   
4                             Neptunia Virtual Stars        0   
5  Monster Energy Supercross - The Official Video...        1   
6                                   Monochrome Order        0   
7                                        Blightbound        1   
8                                           Maquette        0   
9                  FATAL FURY™ BATTLE ARCHIVES VOL.2        0   

   alcohol_reference  animated_blood  blood  blood_and_gore  cartoon_violence  \
0                  0               0      0               0                 0   
1                  0               1      0               0                 0   
2                  0               0      1               0                 0   
3                  0               0      0               0                 0   
4                  0               0      0               0                 0   
5                  0               0      0               0                 0   
6                  0               0      1               0                 0   
7                  0               0      0               1                 0   
8                  1               0      0               0                 0   
9                  0               0      0               0                 0   

   crude_humor  drug_reference  fantasy_violence  ...  sexual_content  \
0            0               0                 0  ...               0   
1            0               0                 0  ...               0   
2            0               0                 0  ...               0   
3            0               0                 1  ...               0   
4            0               0                 1  ...               0   
5            0               0                 0  ...               0   
6            0               0                 0  ...               0   
7            0               0                 0  ...               1   
8            0               0                 0  ...               0   
9            0               0                 0  ...               0   

   sexual_themes  simulated_gambling  strong_janguage  strong_sexual_content  \
0              0                   0                0                      0   
1              0                   0                0                      0   
2              0                   0                1                      0   
3              0                   0                0                      0   
4              0                   0                0                      0   
5              0                   0                0                      0   
6              0                   0                0                      0   
7              0                   0                0                      0   
8              0                   0                0                      0   
9              0                   0                0                      0   

   suggestive_themes  use_of_alcohol  use_of_drugs_and_alcohol  violence  \
0                  0               0                         0         0   
1                  0               0                         0         0   
2                  1               0                         0         0   
3                  0               0                         0         0   
4                  1               0                         0         0   
5                  0               0                         0         0   
6                  0               0                         0         1   
7                  0               0                         0         0   
8                  0               0                         0        

In [3]:
testing_set = pd.read_csv('dataset/test_esrb.csv')
testing_set.head(10)

title  console  alcohol_reference  \
0                                  Still Time        0                  0   
1                           Surf World Series        1                  0   
2      The Metronomicon: Slay the Dance Floor        1                  0   
3                                 Windjammers        0                  0   
4          Rock of Ages 2: Bigger and Boulder        0                  0   
5        South Park: The Fractured but Whole         1                  0   
6           Dishonored: Death of the Outsider        1                  0   
7                         Battle of the Bulge        1                  0   
8                                     F1 2017        1                  0   
9  NARUTO SHIPPUDEN™: Ultimate Ninja® STORM 2        1                  0   

   animated_blood  blood  blood_and_gore  cartoon_violence  crude_humor  \
0               0      1               0                 0            0   
1               0      0               0                 0            0   
2               0      0               1                 0            0   
3               0      0               0                 0            0   
4               0      0               0                 0            1   
5               0      0               1                 0            0   
6               0      0               1                 0            0   
7               0      0               0                 0            0   
8               0      0               0                 0            0   
9               0      0               0                 1            0   

   drug_reference  fantasy_violence  ...  sexual_content  sexual_themes  \
0               0                 0  ...               0              0   
1               0                 0  ...               0              0   
2               0                 1  ...               0              0   
3               0                 0  ...               0              0   
4               0                 0  ...               0              0   
5               0                 0  ...               1              0   
6               0                 0  ...               0              0   
7               0                 1  ...               0              0   
8               0                 0  ...               0              0   
9               0                 0  ...               0              0   

   simulated_gambling  strong_janguage  strong_sexual_content  \
0                   0                0                      0   
1                   0                0                      0   
2                   0                0                      0   
3                   0                0                      0   
4                   0                0                      0   
5                   0                1                      0   
6                   0                0                      0   
7                   0                0                      0   
8                   0                0                      0   
9                   0                0                      0   

   suggestive_themes  use_of_alcohol  use_of_drugs_and_alcohol  violence  \
0                  0               0                         0         1   
1                  0               0                         0         0   
2                  0               0                         0         0   
3                  0               0                         0         0   
4                  0               0                         0         0   
5                  0               0                         0         0   
6                  1               0                         0         0   
7                  0               0                         0         0   
8                  0               0                         0         0   
9                  0               0                         0  

## Check if the traning set and testing set have Nan value

In [4]:
training_set.isnull().sum()

title                       0
console                     0
alcohol_reference           0
animated_blood              0
blood                       0
blood_and_gore              0
cartoon_violence            0
crude_humor                 0
drug_reference              0
fantasy_violence            0
intense_violence            0
language                    0
lyrics                      0
mature_humor                0
mild_blood                  0
mild_cartoon_violence       0
mild_fantasy_violence       0
mild_language               0
mild_lyrics                 0
mild_suggestive_themes      0
mild_violence               0
no_descriptors              0
nudity                      0
partial_nudity              0
sexual_content              0
sexual_themes               0
simulated_gambling          0
strong_janguage             0
strong_sexual_content       0
suggestive_themes           0
use_of_alcohol              0
use_of_drugs_and_alcohol    0
violence                    0
esrb_ratin

In [5]:
testing_set.isnull().sum()

title                       0
console                     0
alcohol_reference           0
animated_blood              0
blood                       0
blood_and_gore              0
cartoon_violence            0
crude_humor                 0
drug_reference              0
fantasy_violence            0
intense_violence            0
language                    0
lyrics                      0
mature_humor                0
mild_blood                  0
mild_cartoon_violence       0
mild_fantasy_violence       0
mild_language               0
mild_lyrics                 0
mild_suggestive_themes      0
mild_violence               0
no_descriptors              0
nudity                      0
partial_nudity              0
sexual_content              0
sexual_themes               0
simulated_gambling          0
strong_janguage             0
strong_sexual_content       0
suggestive_themes           0
use_of_alcohol              0
use_of_drugs_and_alcohol    0
violence                    0
esrb_ratin

# Preprocessing the data

#### - I have deleted the title future from the training set and testing set

In [6]:
training_set.pop('title')
testing_set.pop('title')

0                                  Still Time
1                           Surf World Series
2      The Metronomicon: Slay the Dance Floor
3                                 Windjammers
4          Rock of Ages 2: Bigger and Boulder
                        ...                  
495                                 For Honor
496              Victor Vran Overkill Edition
497                    Danganronpa 1•2 Reload
498                       Touhou Double Focus
499                 Crypt of the Serpent King
Name: title, Length: 500, dtype: object

#### - split the target column from the training set

In [7]:
y = training_set.pop('esrb_rating')
y = y.values

###### - take all the remaining column to save them in X_training : will be used to train the model

In [8]:
X = training_set.iloc[:,:].values 

#### - do the same thing with testing set

In [9]:
y_testing = testing_set.pop('esrb_rating')
y_testing = y_testing.values

###### - take all the remaining column to save them in X_testing : will be used to test the model

In [10]:
X_testing =testing_set.iloc[:,:].values

# Import the required library to building the model

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score,roc_auc_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

## Hyperparameter tuning
######  - using Grid Search approach

In [12]:
param_grid = {'n_estimators':[50,70,100,150],'criterion':('gini', 'entropy'),"max_depth": [3,5,10, None],
              "min_samples_split": [5,6,7,10],'class_weight':('balanced',None)}
rfc = RandomForestClassifier(random_state=0)
clf = GridSearchCV(rfc, param_grid)
clf.fit(X,y)
clf.best_params_ #return the best paramter that increase the accuracy 

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': None,
 'min_samples_split': 10,
 'n_estimators': 50}

## Build the model with optimal hyperparameter

In [21]:
kf = KFold(n_splits=5)
SumAcc=0
fScore=0
RFC = ''
auc=0
SumConf= np.zeros((4,4))
for train, test in kf.split(X):
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    RFC = RandomForestClassifier(criterion='gini',class_weight='balanced',max_depth=None,min_samples_split= 10,n_estimators= 50)
    RFC.fit(X_train,y_train)
    predictions = RFC.predict(X_test)
    SumConf += confusion_matrix(y_test, predictions)
    fScore += f1_score(y_test,predictions,average='weighted')
    SumAcc += accuracy_score(y_test,predictions)
    
print("The Accuracy: " , SumAcc/5) 
print("The Confusion Matrix: " , SumConf/5) 
print("The F1 Score: ", fScore/5)

The Accuracy:  0.8559366754617415
The Confusion Matrix:  [[ 80.8   1.6   0.    0.8]
 [  3.2  69.    0.    8.4]
 [  0.2   0.   68.6   8.6]
 [  2.8  20.4   8.6 106. ]]
The F1 Score:  0.8549092168126021


### testing the model

In [14]:
predictions = RFC.predict(X_testing)
SumConf = confusion_matrix(y_testing, predictions)
fScore = f1_score(y_testing,predictions,average='weighted')
SumAcc = accuracy_score(y_testing,predictions)
print("The Accuracy: " , SumAcc) 
print("The Confusion Matrix: " , SumConf) 
print("The F1 Score: ", fScore)

The Accuracy:  0.838
The Confusion Matrix:  [[ 95   4   0   1]
 [  4 113   0   9]
 [  0   0  62  28]
 [  1  26   8 149]]
The F1 Score:  0.836807768614916


### Create a binary image to the model to use it with the web app

In [15]:
pickle.dump(RFC, open('model.pkl','wb'))